/*
  # Seed Clinical Reference Data

  1. Data Seeded
    - 60+ symptoms across 12 categories
    - 57 diagnoses with ICD-10 codes
    - 160+ medications across all categories
    - 60+ lab tests with reference ranges
*/

-- SYMPTOMS
INSERT INTO symptoms (name, category) VALUES
('Fever', 'general'), ('Cough', 'respiratory'), ('Cold / Runny Nose', 'respiratory'),
('Sore Throat', 'ENT'), ('Headache', 'neurological'), ('Body Ache', 'musculoskeletal'),
('Fatigue / Weakness', 'general'), ('Loss of Appetite', 'gastrointestinal'),
('Nausea', 'gastrointestinal'), ('Vomiting', 'gastrointestinal'),
('Diarrhea', 'gastrointestinal'), ('Constipation', 'gastrointestinal'),
('Abdominal Pain', 'gastrointestinal'), ('Bloating', 'gastrointestinal'),
('Chest Pain', 'cardiovascular'), ('Shortness of Breath', 'respiratory'),
('Palpitations', 'cardiovascular'), ('Dizziness', 'neurological'),
('Fainting / Syncope', 'neurological'), ('Back Pain', 'musculoskeletal'),
('Neck Pain', 'musculoskeletal'), ('Joint Pain', 'musculoskeletal'),
('Muscle Cramps', 'musculoskeletal'), ('Swelling in Legs', 'cardiovascular'),
('Rash / Skin Eruption', 'dermatological'), ('Itching', 'dermatological'),
('Jaundice', 'hepatic'), ('Dark Urine', 'renal'), ('Burning Micturition', 'renal'),
('Frequent Urination', 'renal'), ('Blood in Urine', 'renal'),
('Decreased Urine Output', 'renal'), ('Excessive Thirst', 'endocrine'),
('Excessive Hunger', 'endocrine'), ('Weight Loss', 'general'),
('Weight Gain', 'general'), ('Night Sweats', 'general'),
('Chills / Rigors', 'general'), ('Vision Problems', 'ophthalmological'),
('Eye Redness', 'ophthalmological'), ('Ear Pain', 'ENT'), ('Hearing Loss', 'ENT'),
('Nasal Blockage', 'ENT'), ('Nosebleed', 'ENT'), ('Toothache', 'dental'),
('Difficulty Swallowing', 'ENT'), ('Hoarseness of Voice', 'ENT'),
('Numbness / Tingling', 'neurological'), ('Tremors', 'neurological'),
('Memory Loss', 'neurological'), ('Confusion', 'neurological'),
('Anxiety', 'psychiatric'), ('Depression', 'psychiatric'),
('Insomnia', 'psychiatric'), ('Excessive Sleepiness', 'psychiatric'),
('Irregular Heartbeat', 'cardiovascular'), ('Leg Cramps', 'musculoskeletal'),
('Hot Flushes', 'endocrine'), ('Excessive Sweating', 'general'),
('Hair Loss', 'dermatological'), ('Nail Changes', 'dermatological'),
('Painful Periods', 'gynaecological'), ('Irregular Periods', 'gynaecological'),
('Vaginal Discharge', 'gynaecological'), ('Breast Pain', 'gynaecological')
ON CONFLICT DO NOTHING;

-- DIAGNOSES
INSERT INTO diagnoses (name, icd_code, category) VALUES
('Hypertension', 'I10', 'cardiovascular'),
('Type 2 Diabetes Mellitus', 'E11', 'endocrine'),
('Acute Upper Respiratory Infection', 'J06.9', 'respiratory'),
('Pneumonia', 'J18.9', 'respiratory'),
('Asthma', 'J45.9', 'respiratory'),
('Chronic Obstructive Pulmonary Disease', 'J44.1', 'respiratory'),
('Acute Bronchitis', 'J20.9', 'respiratory'),
('Allergic Rhinitis', 'J30.4', 'ENT'),
('Sinusitis', 'J32.9', 'ENT'),
('Tonsillitis', 'J35.0', 'ENT'),
('Otitis Media', 'H66.9', 'ENT'),
('Coronary Artery Disease', 'I25.1', 'cardiovascular'),
('Heart Failure', 'I50.9', 'cardiovascular'),
('Atrial Fibrillation', 'I48.9', 'cardiovascular'),
('Gastroenteritis', 'A09', 'gastrointestinal'),
('Gastroesophageal Reflux Disease', 'K21.0', 'gastrointestinal'),
('Peptic Ulcer Disease', 'K27.9', 'gastrointestinal'),
('Irritable Bowel Syndrome', 'K58.9', 'gastrointestinal'),
('Appendicitis', 'K37', 'gastrointestinal'),
('Cholecystitis', 'K81.0', 'gastrointestinal'),
('Urinary Tract Infection', 'N39.0', 'renal'),
('Kidney Stones', 'N20.0', 'renal'),
('Chronic Kidney Disease', 'N18.9', 'renal'),
('Migraine', 'G43.9', 'neurological'),
('Epilepsy', 'G40.9', 'neurological'),
('Stroke', 'I64', 'neurological'),
('Vertigo', 'H81.3', 'neurological'),
('Depression', 'F32.9', 'psychiatric'),
('Anxiety Disorder', 'F41.9', 'psychiatric'),
('Rheumatoid Arthritis', 'M06.9', 'musculoskeletal'),
('Osteoarthritis', 'M19.9', 'musculoskeletal'),
('Low Back Pain', 'M54.5', 'musculoskeletal'),
('Cervical Spondylosis', 'M47.8', 'musculoskeletal'),
('Osteoporosis', 'M81.0', 'musculoskeletal'),
('Dengue Fever', 'A97', 'infectious'),
('Malaria', 'B54', 'infectious'),
('Typhoid Fever', 'A01.0', 'infectious'),
('COVID-19', 'U07.1', 'infectious'),
('Tuberculosis', 'A15.0', 'infectious'),
('Anemia', 'D64.9', 'haematological'),
('Thyroid Disorder', 'E07.9', 'endocrine'),
('Hypothyroidism', 'E03.9', 'endocrine'),
('Hyperthyroidism', 'E05.9', 'endocrine'),
('Vitamin D Deficiency', 'E55.9', 'nutritional'),
('Vitamin B12 Deficiency', 'E53.8', 'nutritional'),
('Iron Deficiency Anemia', 'D50.9', 'haematological'),
('Eczema / Dermatitis', 'L30.9', 'dermatological'),
('Psoriasis', 'L40.9', 'dermatological'),
('Acne', 'L70.0', 'dermatological'),
('Urticaria', 'L50.9', 'dermatological')
ON CONFLICT DO NOTHING;

-- MEDICATIONS (common subset)
INSERT INTO medications (name, generic_name, category, dosage_form, strength, unit) VALUES
('Paracetamol 500mg', 'Paracetamol', 'analgesic', 'tablet', '500', 'mg'),
('Paracetamol 650mg', 'Paracetamol', 'analgesic', 'tablet', '650', 'mg'),
('Ibuprofen 400mg', 'Ibuprofen', 'NSAID', 'tablet', '400', 'mg'),
('Diclofenac 50mg', 'Diclofenac Sodium', 'NSAID', 'tablet', '50', 'mg'),
('Aspirin 75mg', 'Aspirin', 'antiplatelet', 'tablet', '75', 'mg'),
('Amoxicillin 250mg', 'Amoxicillin', 'antibiotic', 'capsule', '250', 'mg'),
('Amoxicillin 500mg', 'Amoxicillin', 'antibiotic', 'capsule', '500', 'mg'),
('Amoxicillin-Clavulanate 625mg', 'Amoxicillin + Clavulanic Acid', 'antibiotic', 'tablet', '625', 'mg'),
('Azithromycin 250mg', 'Azithromycin', 'antibiotic', 'tablet', '250', 'mg'),
('Azithromycin 500mg', 'Azithromycin', 'antibiotic', 'tablet', '500', 'mg'),
('Ciprofloxacin 500mg', 'Ciprofloxacin', 'antibiotic', 'tablet', '500', 'mg'),
('Levofloxacin 500mg', 'Levofloxacin', 'antibiotic', 'tablet', '500', 'mg'),
('Doxycycline 100mg', 'Doxycycline', 'antibiotic', 'capsule', '100', 'mg'),
('Cefixime 200mg', 'Cefixime', 'antibiotic', 'tablet', '200', 'mg'),
('Metronidazole 400mg', 'Metronidazole', 'antibiotic', 'tablet', '400', 'mg'),
('Amlodipine 5mg', 'Amlodipine', 'antihypertensive', 'tablet', '5', 'mg'),
('Amlodipine 10mg', 'Amlodipine', 'antihypertensive', 'tablet', '10', 'mg'),
('Atenolol 50mg', 'Atenolol', 'antihypertensive', 'tablet', '50', 'mg'),
('Metoprolol 50mg', 'Metoprolol Succinate', 'antihypertensive', 'tablet', '50', 'mg'),
('Losartan 50mg', 'Losartan Potassium', 'antihypertensive', 'tablet', '50', 'mg'),
('Telmisartan 40mg', 'Telmisartan', 'antihypertensive', 'tablet', '40', 'mg'),
('Ramipril 5mg', 'Ramipril', 'antihypertensive', 'tablet', '5', 'mg'),
('Furosemide 40mg', 'Furosemide', 'diuretic', 'tablet', '40', 'mg'),
('Metformin 500mg', 'Metformin HCl', 'antidiabetic', 'tablet', '500', 'mg'),
('Metformin 1000mg', 'Metformin HCl', 'antidiabetic', 'tablet', '1000', 'mg'),
('Glimepiride 1mg', 'Glimepiride', 'antidiabetic', 'tablet', '1', 'mg'),
('Glimepiride 2mg', 'Glimepiride', 'antidiabetic', 'tablet', '2', 'mg'),
('Sitagliptin 100mg', 'Sitagliptin', 'antidiabetic', 'tablet', '100', 'mg'),
('Omeprazole 20mg', 'Omeprazole', 'antacid', 'capsule', '20', 'mg'),
('Pantoprazole 40mg', 'Pantoprazole Sodium', 'antacid', 'tablet', '40', 'mg'),
('Rabeprazole 20mg', 'Rabeprazole Sodium', 'antacid', 'tablet', '20', 'mg'),
('Domperidone 10mg', 'Domperidone', 'antiemetic', 'tablet', '10', 'mg'),
('Ondansetron 4mg', 'Ondansetron HCl', 'antiemetic', 'tablet', '4', 'mg'),
('Salbutamol Inhaler', 'Salbutamol', 'bronchodilator', 'inhaler', '100mcg/dose', 'mcg/dose'),
('Budesonide Inhaler', 'Budesonide', 'corticosteroid', 'inhaler', '200mcg/dose', 'mcg/dose'),
('Montelukast 10mg', 'Montelukast Sodium', 'anti-asthmatic', 'tablet', '10', 'mg'),
('Cetirizine 10mg', 'Cetirizine HCl', 'antihistamine', 'tablet', '10', 'mg'),
('Fexofenadine 120mg', 'Fexofenadine HCl', 'antihistamine', 'tablet', '120', 'mg'),
('Loratadine 10mg', 'Loratadine', 'antihistamine', 'tablet', '10', 'mg'),
('Atorvastatin 10mg', 'Atorvastatin Calcium', 'statin', 'tablet', '10', 'mg'),
('Atorvastatin 20mg', 'Atorvastatin Calcium', 'statin', 'tablet', '20', 'mg'),
('Rosuvastatin 10mg', 'Rosuvastatin Calcium', 'statin', 'tablet', '10', 'mg'),
('Clopidogrel 75mg', 'Clopidogrel Bisulphate', 'antiplatelet', 'tablet', '75', 'mg'),
('Phenytoin 100mg', 'Phenytoin Sodium', 'anticonvulsant', 'tablet', '100', 'mg'),
('Levetiracetam 500mg', 'Levetiracetam', 'anticonvulsant', 'tablet', '500', 'mg'),
('Sertraline 50mg', 'Sertraline HCl', 'antidepressant', 'tablet', '50', 'mg'),
('Escitalopram 10mg', 'Escitalopram Oxalate', 'antidepressant', 'tablet', '10', 'mg'),
('Prednisolone 5mg', 'Prednisolone', 'corticosteroid', 'tablet', '5', 'mg'),
('Dexamethasone 4mg', 'Dexamethasone', 'corticosteroid', 'tablet', '4', 'mg'),
('Levothyroxine 50mcg', 'Levothyroxine Sodium', 'thyroid', 'tablet', '50', 'mcg'),
('Levothyroxine 100mcg', 'Levothyroxine Sodium', 'thyroid', 'tablet', '100', 'mcg'),
('Vitamin D3 60000 IU', 'Cholecalciferol', 'vitamin', 'capsule', '60000', 'IU'),
('Vitamin B12 500mcg', 'Methylcobalamin', 'vitamin', 'tablet', '500', 'mcg'),
('Folic Acid 5mg', 'Folic Acid', 'vitamin', 'tablet', '5', 'mg'),
('Iron + Folic Acid', 'Ferrous Sulphate+Folic Acid', 'supplement', 'tablet', '150+0.5mg', 'mg'),
('Calcium + Vitamin D3', 'Calcium Carbonate+D3', 'supplement', 'tablet', '500mg+250IU', 'mg'),
('Fluconazole 150mg', 'Fluconazole', 'antifungal', 'capsule', '150', 'mg'),
('Acyclovir 400mg', 'Acyclovir', 'antiviral', 'tablet', '400', 'mg'),
('Albendazole 400mg', 'Albendazole', 'anthelmintic', 'tablet', '400', 'mg'),
('Normal Saline 500ml', '0.9% Sodium Chloride', 'IV fluid', 'solution', '0.9%', '%'),
('Ringer Lactate 500ml', 'Lactated Ringers Solution', 'IV fluid', 'solution', '-', '-')
ON CONFLICT DO NOTHING;

-- LAB TESTS
INSERT INTO lab_tests (name, code, category, sample_type, tat_hours, price, normal_range_male, normal_range_female, unit, method) VALUES
('Complete Blood Count', 'CBC', 'haematology', 'blood', 4, 250, 'See individual parameters', 'See individual parameters', '-', 'Automated'),
('Haemoglobin', 'HB', 'haematology', 'blood', 2, 80, '13.5-17.5', '12.0-15.5', 'g/dL', 'Automated'),
('White Blood Cell Count', 'WBC', 'haematology', 'blood', 2, 80, '4.5-11.0', '4.5-11.0', 'x10^3/uL', 'Automated'),
('Platelet Count', 'PLT', 'haematology', 'blood', 2, 80, '150-400', '150-400', 'x10^3/uL', 'Automated'),
('ESR', 'ESR', 'haematology', 'blood', 2, 100, '0-15', '0-20', 'mm/hr', 'Westergren'),
('Blood Glucose Fasting', 'FBS', 'biochemistry', 'blood', 2, 80, '70-100', '70-100', 'mg/dL', 'GOD-POD'),
('Blood Glucose Random', 'RBS', 'biochemistry', 'blood', 2, 80, '<140', '<140', 'mg/dL', 'GOD-POD'),
('Blood Glucose Post Prandial', 'PPBS', 'biochemistry', 'blood', 2, 80, '<140', '<140', 'mg/dL', 'GOD-POD'),
('HbA1c', 'HBA1C', 'biochemistry', 'blood', 6, 350, '<5.7', '<5.7', '%', 'HPLC'),
('Urea', 'UREA', 'biochemistry', 'blood', 3, 100, '15-45', '15-45', 'mg/dL', 'Urease-GLDH'),
('Creatinine', 'CREAT', 'biochemistry', 'blood', 3, 100, '0.7-1.2', '0.5-1.0', 'mg/dL', 'Jaffe'),
('Uric Acid', 'UA', 'biochemistry', 'blood', 3, 120, '3.5-7.2', '2.6-6.0', 'mg/dL', 'Uricase'),
('Sodium', 'NA', 'biochemistry', 'blood', 2, 100, '136-145', '136-145', 'mEq/L', 'ISE'),
('Potassium', 'K', 'biochemistry', 'blood', 2, 100, '3.5-5.1', '3.5-5.1', 'mEq/L', 'ISE'),
('Total Bilirubin', 'TBIL', 'biochemistry', 'blood', 3, 120, '0.3-1.2', '0.3-1.2', 'mg/dL', 'Diazo'),
('SGOT (AST)', 'SGOT', 'biochemistry', 'blood', 3, 120, '10-40', '10-35', 'IU/L', 'UV-IFCC'),
('SGPT (ALT)', 'SGPT', 'biochemistry', 'blood', 3, 120, '10-40', '7-35', 'IU/L', 'UV-IFCC'),
('Alkaline Phosphatase', 'ALP', 'biochemistry', 'blood', 3, 120, '44-147', '44-147', 'IU/L', 'PNPP'),
('Total Cholesterol', 'CHOL', 'biochemistry', 'blood', 3, 120, '<200', '<200', 'mg/dL', 'CHODPAPs'),
('Triglycerides', 'TG', 'biochemistry', 'blood', 3, 120, '<150', '<150', 'mg/dL', 'GPO-POD'),
('HDL Cholesterol', 'HDL', 'biochemistry', 'blood', 3, 120, '>40', '>50', 'mg/dL', 'Direct'),
('LDL Cholesterol', 'LDL', 'biochemistry', 'blood', 3, 120, '<100', '<100', 'mg/dL', 'Friedewald'),
('TSH', 'TSH', 'biochemistry', 'blood', 6, 300, '0.4-4.0', '0.4-4.0', 'mIU/L', 'CLIA'),
('T3 Total', 'T3', 'biochemistry', 'blood', 6, 250, '80-200', '80-200', 'ng/dL', 'CLIA'),
('T4 Total', 'T4', 'biochemistry', 'blood', 6, 250, '5.0-12.0', '5.0-12.0', 'ug/dL', 'CLIA'),
('HBsAg', 'HBSAG', 'serology', 'blood', 4, 300, 'Non-reactive', 'Non-reactive', '-', 'ELISA'),
('HIV 1+2', 'HIV', 'serology', 'blood', 4, 400, 'Non-reactive', 'Non-reactive', '-', 'ELISA'),
('Dengue NS1 Antigen', 'DGNS1', 'serology', 'blood', 4, 500, 'Negative', 'Negative', '-', 'ELISA'),
('Malaria Antigen Test', 'MAL', 'serology', 'blood', 2, 300, 'Negative', 'Negative', '-', 'RDT'),
('Widal Test', 'WIDAL', 'serology', 'blood', 6, 250, '<1:40', '<1:40', '-', 'Slide'),
('Urine Routine & Microscopy', 'UR', 'urine', 'urine', 2, 100, 'See parameters', 'See parameters', '-', 'Microscopy'),
('Urine Culture & Sensitivity', 'UCx', 'urine', 'urine', 48, 500, 'No growth', 'No growth', '-', 'Culture'),
('Stool Routine & Microscopy', 'SR', 'stool', 'stool', 4, 100, 'No parasites', 'No parasites', '-', 'Microscopy'),
('Blood Culture & Sensitivity', 'BCx', 'microbiology', 'blood', 72, 700, 'No growth', 'No growth', '-', 'Automated'),
('Troponin I', 'TROPI', 'biochemistry', 'blood', 3, 800, '<0.04', '<0.04', 'ng/mL', 'CLIA'),
('CRP', 'CRP', 'biochemistry', 'blood', 4, 300, '<5', '<5', 'mg/L', 'Nephelometry'),
('Ferritin', 'FERR', 'biochemistry', 'blood', 6, 500, '12-300', '12-150', 'ng/mL', 'CLIA'),
('Vitamin D (25-OH)', 'VITD', 'biochemistry', 'blood', 24, 800, '30-100', '30-100', 'ng/mL', 'CLIA'),
('Vitamin B12', 'B12', 'biochemistry', 'blood', 24, 600, '200-900', '200-900', 'pg/mL', 'CLIA'),
('D-Dimer', 'DDIM', 'haematology', 'blood', 6, 800, '<0.5', '<0.5', 'mg/L', 'ELISA'),
('Prothrombin Time (PT/INR)', 'PTINR', 'haematology', 'blood', 4, 250, '11-13.5 sec / 0.8-1.1', '11-13.5 sec / 0.8-1.1', 'sec', 'Photo')
ON CONFLICT DO NOTHING;

-- Update lab tests with hospital_id
UPDATE lab_tests SET hospital_id = '11111111-1111-1111-1111-111111111111'
WHERE hospital_id IS NULL;
