/*
  # Seed Medications Database

  ## Summary
  Populates the medications table with 200+ commonly prescribed drugs across
  various therapeutic categories including antibiotics, analgesics, antihypertensives,
  antidiabetics, GI medications, respiratory drugs, and more.

  ## Notes
  - Uses lowercase form values per table constraint
  - Uses ON CONFLICT DO NOTHING to prevent duplicate errors
*/

INSERT INTO medications (generic_name, brand_name, category, form, strength, usage_count) VALUES
-- Antibiotics
('Amoxicillin', 'Mox', 'Antibiotics', 'capsule', '500mg', 150),
('Amoxicillin', 'Mox', 'Antibiotics', 'capsule', '250mg', 120),
('Amoxicillin + Clavulanic Acid', 'Augmentin', 'Antibiotics', 'tablet', '625mg', 145),
('Amoxicillin + Clavulanic Acid', 'Augmentin', 'Antibiotics', 'tablet', '375mg', 100),
('Azithromycin', 'Azithral', 'Antibiotics', 'tablet', '500mg', 140),
('Azithromycin', 'Azithral', 'Antibiotics', 'tablet', '250mg', 110),
('Azithromycin', 'Zithromax', 'Antibiotics', 'syrup', '200mg/5ml', 80),
('Ciprofloxacin', 'Ciplox', 'Antibiotics', 'tablet', '500mg', 130),
('Ciprofloxacin', 'Ciplox', 'Antibiotics', 'tablet', '250mg', 90),
('Levofloxacin', 'Levomac', 'Antibiotics', 'tablet', '500mg', 120),
('Levofloxacin', 'Levomac', 'Antibiotics', 'tablet', '750mg', 70),
('Ofloxacin', 'Oflox', 'Antibiotics', 'tablet', '200mg', 85),
('Ofloxacin', 'Oflox', 'Antibiotics', 'tablet', '400mg', 65),
('Cefixime', 'Taxim-O', 'Antibiotics', 'tablet', '200mg', 110),
('Cefixime', 'Taxim-O', 'Antibiotics', 'tablet', '100mg', 75),
('Cefixime', 'Taxim-O', 'Antibiotics', 'syrup', '50mg/5ml', 60),
('Cefpodoxime', 'Cepodem', 'Antibiotics', 'tablet', '200mg', 95),
('Cefuroxime', 'Ceftum', 'Antibiotics', 'tablet', '500mg', 80),
('Cefuroxime', 'Ceftum', 'Antibiotics', 'tablet', '250mg', 70),
('Metronidazole', 'Flagyl', 'Antibiotics', 'tablet', '400mg', 100),
('Metronidazole', 'Flagyl', 'Antibiotics', 'tablet', '200mg', 75),
('Doxycycline', 'Doxt', 'Antibiotics', 'capsule', '100mg', 90),
('Norfloxacin', 'Norflox', 'Antibiotics', 'tablet', '400mg', 60),
('Nitrofurantoin', 'Furadantin', 'Antibiotics', 'capsule', '100mg', 55),
('Cephalexin', 'Phexin', 'Antibiotics', 'capsule', '500mg', 70),
('Clarithromycin', 'Claribid', 'Antibiotics', 'tablet', '500mg', 65),
('Clindamycin', 'Dalacin C', 'Antibiotics', 'capsule', '300mg', 45),

-- Analgesics & NSAIDs
('Paracetamol', 'Crocin', 'Analgesics', 'tablet', '500mg', 200),
('Paracetamol', 'Dolo', 'Analgesics', 'tablet', '650mg', 190),
('Paracetamol', 'Calpol', 'Analgesics', 'syrup', '120mg/5ml', 150),
('Ibuprofen', 'Brufen', 'Analgesics', 'tablet', '400mg', 160),
('Ibuprofen', 'Brufen', 'Analgesics', 'tablet', '200mg', 130),
('Ibuprofen + Paracetamol', 'Combiflam', 'Analgesics', 'tablet', '400mg+325mg', 180),
('Diclofenac', 'Voveran', 'Analgesics', 'tablet', '50mg', 140),
('Diclofenac', 'Voveran SR', 'Analgesics', 'tablet', '100mg', 110),
('Diclofenac', 'Voveran', 'Analgesics', 'gel', '1%', 85),
('Aceclofenac', 'Zerodol', 'Analgesics', 'tablet', '100mg', 130),
('Aceclofenac + Paracetamol', 'Zerodol-P', 'Analgesics', 'tablet', '100mg+325mg', 145),
('Naproxen', 'Naprosyn', 'Analgesics', 'tablet', '500mg', 70),
('Nimesulide', 'Nimulid', 'Analgesics', 'tablet', '100mg', 90),
('Nimesulide + Paracetamol', 'Nimulid-P', 'Analgesics', 'tablet', '100mg+325mg', 100),
('Etoricoxib', 'Arcoxia', 'Analgesics', 'tablet', '90mg', 65),
('Etoricoxib', 'Arcoxia', 'Analgesics', 'tablet', '60mg', 60),
('Tramadol', 'Ultracet', 'Analgesics', 'tablet', '37.5mg+325mg', 55),
('Piroxicam', 'Dolonex', 'Analgesics', 'capsule', '20mg', 40),

-- Antihypertensives
('Amlodipine', 'Amlong', 'Antihypertensives', 'tablet', '5mg', 140),
('Amlodipine', 'Amlong', 'Antihypertensives', 'tablet', '10mg', 100),
('Telmisartan', 'Telma', 'Antihypertensives', 'tablet', '40mg', 130),
('Telmisartan', 'Telma', 'Antihypertensives', 'tablet', '80mg', 90),
('Telmisartan + Amlodipine', 'Telma-AM', 'Antihypertensives', 'tablet', '40mg+5mg', 110),
('Losartan', 'Losar', 'Antihypertensives', 'tablet', '50mg', 100),
('Losartan', 'Losar', 'Antihypertensives', 'tablet', '25mg', 70),
('Olmesartan', 'Olmat', 'Antihypertensives', 'tablet', '20mg', 85),
('Ramipril', 'Cardace', 'Antihypertensives', 'tablet', '5mg', 80),
('Ramipril', 'Cardace', 'Antihypertensives', 'tablet', '2.5mg', 65),
('Enalapril', 'Enam', 'Antihypertensives', 'tablet', '5mg', 70),
('Atenolol', 'Aten', 'Antihypertensives', 'tablet', '50mg', 90),
('Atenolol', 'Aten', 'Antihypertensives', 'tablet', '25mg', 75),
('Metoprolol', 'Betaloc', 'Antihypertensives', 'tablet', '50mg', 85),
('Metoprolol', 'Betaloc', 'Antihypertensives', 'tablet', '25mg', 70),
('Nebivolol', 'Nebicard', 'Antihypertensives', 'tablet', '5mg', 60),
('Carvedilol', 'Carca', 'Antihypertensives', 'tablet', '6.25mg', 55),
('Hydrochlorothiazide', 'Aquazide', 'Antihypertensives', 'tablet', '12.5mg', 50),
('Furosemide', 'Lasix', 'Antihypertensives', 'tablet', '40mg', 75),
('Spironolactone', 'Aldactone', 'Antihypertensives', 'tablet', '25mg', 45),

-- Antidiabetics
('Metformin', 'Glycomet', 'Antidiabetics', 'tablet', '500mg', 150),
('Metformin', 'Glycomet', 'Antidiabetics', 'tablet', '850mg', 100),
('Metformin', 'Glycomet SR', 'Antidiabetics', 'tablet', '1000mg', 80),
('Glimepiride', 'Amaryl', 'Antidiabetics', 'tablet', '1mg', 90),
('Glimepiride', 'Amaryl', 'Antidiabetics', 'tablet', '2mg', 85),
('Glimepiride + Metformin', 'Amaryl-M', 'Antidiabetics', 'tablet', '1mg+500mg', 110),
('Glimepiride + Metformin', 'Amaryl-M', 'Antidiabetics', 'tablet', '2mg+500mg', 95),
('Gliclazide', 'Diamicron', 'Antidiabetics', 'tablet', '80mg', 70),
('Sitagliptin', 'Januvia', 'Antidiabetics', 'tablet', '100mg', 60),
('Sitagliptin + Metformin', 'Janumet', 'Antidiabetics', 'tablet', '50mg+500mg', 55),
('Vildagliptin', 'Galvus', 'Antidiabetics', 'tablet', '50mg', 50),
('Vildagliptin + Metformin', 'Galvus Met', 'Antidiabetics', 'tablet', '50mg+500mg', 65),
('Empagliflozin', 'Jardiance', 'Antidiabetics', 'tablet', '10mg', 45),
('Dapagliflozin', 'Forxiga', 'Antidiabetics', 'tablet', '10mg', 45),
('Pioglitazone', 'Pioz', 'Antidiabetics', 'tablet', '15mg', 35),
('Insulin Glargine', 'Lantus', 'Antidiabetics', 'injection', '100IU/ml', 30),

-- Gastrointestinal
('Omeprazole', 'Omez', 'Gastrointestinal', 'capsule', '20mg', 180),
('Omeprazole', 'Omez', 'Gastrointestinal', 'capsule', '40mg', 120),
('Pantoprazole', 'Pan', 'Gastrointestinal', 'tablet', '40mg', 170),
('Pantoprazole', 'Pantocid', 'Gastrointestinal', 'tablet', '40mg', 160),
('Esomeprazole', 'Nexpro', 'Gastrointestinal', 'tablet', '40mg', 100),
('Rabeprazole', 'Razo', 'Gastrointestinal', 'tablet', '20mg', 130),
('Rabeprazole + Domperidone', 'Razo-D', 'Gastrointestinal', 'capsule', '20mg+30mg', 140),
('Domperidone', 'Domstal', 'Gastrointestinal', 'tablet', '10mg', 150),
('Ondansetron', 'Emeset', 'Gastrointestinal', 'tablet', '4mg', 110),
('Ondansetron', 'Emeset', 'Gastrointestinal', 'tablet', '8mg', 80),
('Metoclopramide', 'Perinorm', 'Gastrointestinal', 'tablet', '10mg', 90),
('Sucralfate', 'Sucrafil', 'Gastrointestinal', 'tablet', '1g', 70),
('Loperamide', 'Eldoper', 'Gastrointestinal', 'capsule', '2mg', 60),
('ORS', 'Electral', 'Gastrointestinal', 'powder', 'Sachet', 120),
('Rifaximin', 'Rifagut', 'Gastrointestinal', 'tablet', '400mg', 55),
('Lactulose', 'Duphalac', 'Gastrointestinal', 'syrup', '10g/15ml', 65),
('Ispaghula Husk', 'Isabgol', 'Gastrointestinal', 'powder', '3.5g', 50),
('Antacid Gel', 'Digene', 'Gastrointestinal', 'gel', '15ml', 100),
('Dicyclomine', 'Cyclopam', 'Gastrointestinal', 'tablet', '10mg', 85),
('Dicyclomine + Paracetamol', 'Cyclopam-P', 'Gastrointestinal', 'tablet', '10mg+325mg', 90),

-- Respiratory
('Salbutamol', 'Asthalin', 'Respiratory', 'tablet', '4mg', 100),
('Salbutamol', 'Asthalin', 'Respiratory', 'syrup', '2mg/5ml', 90),
('Salbutamol', 'Asthalin', 'Respiratory', 'inhaler', '100mcg', 130),
('Levosalbutamol', 'Levolin', 'Respiratory', 'inhaler', '50mcg', 80),
('Montelukast', 'Montair', 'Respiratory', 'tablet', '10mg', 120),
('Montelukast', 'Montair', 'Respiratory', 'tablet', '5mg', 75),
('Montelukast + Levocetirizine', 'Montair-LC', 'Respiratory', 'tablet', '10mg+5mg', 140),
('Theophylline', 'Deriphyllin', 'Respiratory', 'tablet', '150mg', 60),
('Dextromethorphan', 'Benadryl DR', 'Respiratory', 'syrup', '10mg/5ml', 80),
('Ambroxol', 'Mucolite', 'Respiratory', 'syrup', '30mg/5ml', 95),
('Ambroxol', 'Mucolite', 'Respiratory', 'tablet', '30mg', 70),
('Bromhexine', 'Solvin', 'Respiratory', 'syrup', '4mg/5ml', 65),
('Guaifenesin', 'Glycodin', 'Respiratory', 'syrup', '100mg/5ml', 75),
('Budesonide', 'Budecort', 'Respiratory', 'inhaler', '200mcg', 55),
('Fluticasone', 'Flohale', 'Respiratory', 'inhaler', '125mcg', 50),
('Codeine + Chlorpheniramine', 'Corex', 'Respiratory', 'syrup', '10mg/5ml', 40),

-- Antihistamines
('Cetirizine', 'Cetzine', 'Antihistamines', 'tablet', '10mg', 160),
('Cetirizine', 'Cetzine', 'Antihistamines', 'syrup', '5mg/5ml', 90),
('Levocetirizine', 'Xyzal', 'Antihistamines', 'tablet', '5mg', 150),
('Fexofenadine', 'Allegra', 'Antihistamines', 'tablet', '120mg', 100),
('Fexofenadine', 'Allegra', 'Antihistamines', 'tablet', '180mg', 70),
('Loratadine', 'Claritin', 'Antihistamines', 'tablet', '10mg', 80),
('Desloratadine', 'Deslor', 'Antihistamines', 'tablet', '5mg', 60),
('Chlorpheniramine', 'Piriton', 'Antihistamines', 'tablet', '4mg', 70),
('Hydroxyzine', 'Atarax', 'Antihistamines', 'tablet', '25mg', 55),
('Promethazine', 'Phenergan', 'Antihistamines', 'tablet', '25mg', 50),
('Montelukast + Fexofenadine', 'Montair-FX', 'Antihistamines', 'tablet', '10mg+120mg', 65),

-- Cardiovascular
('Atorvastatin', 'Atorva', 'Cardiovascular', 'tablet', '10mg', 120),
('Atorvastatin', 'Atorva', 'Cardiovascular', 'tablet', '20mg', 100),
('Atorvastatin', 'Atorva', 'Cardiovascular', 'tablet', '40mg', 70),
('Rosuvastatin', 'Rozavel', 'Cardiovascular', 'tablet', '10mg', 110),
('Rosuvastatin', 'Rozavel', 'Cardiovascular', 'tablet', '20mg', 80),
('Rosuvastatin', 'Rozavel', 'Cardiovascular', 'tablet', '5mg', 65),
('Aspirin', 'Ecosprin', 'Cardiovascular', 'tablet', '75mg', 140),
('Aspirin', 'Ecosprin', 'Cardiovascular', 'tablet', '150mg', 90),
('Clopidogrel', 'Clopilet', 'Cardiovascular', 'tablet', '75mg', 100),
('Clopidogrel + Aspirin', 'Clopilet-A', 'Cardiovascular', 'tablet', '75mg+75mg', 85),
('Warfarin', 'Warf', 'Cardiovascular', 'tablet', '5mg', 45),
('Rivaroxaban', 'Xarelto', 'Cardiovascular', 'tablet', '10mg', 40),
('Nitroglycerin', 'Sorbitrate', 'Cardiovascular', 'tablet', '5mg', 55),
('Isosorbide Mononitrate', 'Monotrate', 'Cardiovascular', 'tablet', '20mg', 50),

-- Vitamins
('Vitamin B Complex', 'Becosules', 'Vitamins', 'capsule', '-', 130),
('Vitamin B12', 'Neurobion', 'Vitamins', 'tablet', '500mcg', 100),
('Methylcobalamin', 'Mecobalamin', 'Vitamins', 'tablet', '1500mcg', 90),
('Folic Acid', 'Folvite', 'Vitamins', 'tablet', '5mg', 110),
('Iron + Folic Acid', 'Autrin', 'Vitamins', 'tablet', '100mg+500mcg', 95),
('Vitamin D3', 'Calcirol', 'Vitamins', 'powder', '60000IU', 120),
('Vitamin D3', 'Uprise-D3', 'Vitamins', 'tablet', '1000IU', 85),
('Calcium + Vitamin D3', 'Shelcal', 'Vitamins', 'tablet', '500mg+250IU', 100),
('Calcium + Vitamin D3', 'Calcimax', 'Vitamins', 'tablet', '500mg+200IU', 80),
('Vitamin C', 'Limcee', 'Vitamins', 'tablet', '500mg', 90),
('Zinc', 'Zincovit', 'Vitamins', 'tablet', '20mg', 75),
('Multivitamin', 'Supradyn', 'Vitamins', 'tablet', '-', 85),
('Omega-3 Fatty Acids', 'Maxepa', 'Vitamins', 'capsule', '1000mg', 55),
('Vitamin E', 'Evion', 'Vitamins', 'capsule', '400mg', 50),

-- Antidepressants & CNS
('Escitalopram', 'Nexito', 'Antidepressants', 'tablet', '10mg', 70),
('Escitalopram', 'Nexito', 'Antidepressants', 'tablet', '5mg', 55),
('Sertraline', 'Daxid', 'Antidepressants', 'tablet', '50mg', 60),
('Fluoxetine', 'Flunil', 'Antidepressants', 'capsule', '20mg', 50),
('Amitriptyline', 'Tryptomer', 'Antidepressants', 'tablet', '25mg', 55),
('Clonazepam', 'Clonotril', 'Antidepressants', 'tablet', '0.5mg', 65),
('Alprazolam', 'Alprax', 'Antidepressants', 'tablet', '0.25mg', 60),
('Alprazolam', 'Alprax', 'Antidepressants', 'tablet', '0.5mg', 50),
('Pregabalin', 'Lyrica', 'Antidepressants', 'capsule', '75mg', 45),
('Gabapentin', 'Gabapin', 'Antidepressants', 'capsule', '300mg', 40),

-- Dermatological
('Clotrimazole', 'Candid', 'Dermatological', 'cream', '1%', 80),
('Clotrimazole + Beclomethasone', 'Candid-B', 'Dermatological', 'cream', '1%', 90),
('Ketoconazole', 'Nizoral', 'Dermatological', 'cream', '2%', 70),
('Terbinafine', 'Terbicip', 'Dermatological', 'cream', '1%', 55),
('Fluconazole', 'Flucos', 'Dermatological', 'tablet', '150mg', 65),
('Miconazole', 'Daktarin', 'Dermatological', 'gel', '2%', 40),
('Fusidic Acid', 'Fucidin', 'Dermatological', 'cream', '2%', 50),
('Mupirocin', 'T-Bact', 'Dermatological', 'cream', '2%', 55),
('Betamethasone', 'Betnovate', 'Dermatological', 'cream', '0.1%', 75),
('Clobetasol', 'Tenovate', 'Dermatological', 'cream', '0.05%', 45),
('Calamine Lotion', 'Lacto Calamine', 'Dermatological', 'lotion', '-', 70),
('Permethrin', 'Permithrax', 'Dermatological', 'lotion', '5%', 35),
('Benzoyl Peroxide', 'Brevoxyl', 'Dermatological', 'gel', '2.5%', 45),
('Adapalene', 'Adiff', 'Dermatological', 'gel', '0.1%', 40),

-- Ophthalmological
('Ciprofloxacin Eye Drops', 'Ciplox Eye', 'Ophthalmological', 'drops', '0.3%', 60),
('Moxifloxacin Eye Drops', 'Moxicip', 'Ophthalmological', 'drops', '0.5%', 55),
('Ofloxacin Eye Drops', 'Exocin', 'Ophthalmological', 'drops', '0.3%', 50),
('Tobramycin Eye Drops', 'Tobradex', 'Ophthalmological', 'drops', '0.3%', 40),
('Carboxymethylcellulose', 'Refresh Tears', 'Ophthalmological', 'drops', '0.5%', 70),
('Prednisolone Eye Drops', 'Pred Forte', 'Ophthalmological', 'drops', '1%', 35),
('Timolol Eye Drops', 'Glucomol', 'Ophthalmological', 'drops', '0.5%', 30),

-- Muscle Relaxants
('Thiocolchicoside', 'Myoril', 'Muscle Relaxants', 'capsule', '4mg', 70),
('Thiocolchicoside', 'Myoril', 'Muscle Relaxants', 'tablet', '8mg', 55),
('Chlorzoxazone + Paracetamol', 'Flexon', 'Muscle Relaxants', 'tablet', '250mg+500mg', 80),
('Tizanidine', 'Sirdalud', 'Muscle Relaxants', 'tablet', '2mg', 50),
('Cyclobenzaprine', 'Flexeril', 'Muscle Relaxants', 'tablet', '10mg', 35),
('Eperisone', 'Myonal', 'Muscle Relaxants', 'tablet', '50mg', 45),

-- Steroids
('Prednisolone', 'Wysolone', 'Steroids', 'tablet', '5mg', 80),
('Prednisolone', 'Wysolone', 'Steroids', 'tablet', '10mg', 65),
('Prednisolone', 'Wysolone', 'Steroids', 'tablet', '20mg', 50),
('Methylprednisolone', 'Medrol', 'Steroids', 'tablet', '4mg', 55),
('Methylprednisolone', 'Medrol', 'Steroids', 'tablet', '8mg', 45),
('Dexamethasone', 'Dexona', 'Steroids', 'tablet', '0.5mg', 60),
('Deflazacort', 'Defcort', 'Steroids', 'tablet', '6mg', 50),
('Hydrocortisone', 'Efcorlin', 'Steroids', 'cream', '1%', 40),

-- Thyroid
('Levothyroxine', 'Thyronorm', 'Thyroid', 'tablet', '25mcg', 70),
('Levothyroxine', 'Thyronorm', 'Thyroid', 'tablet', '50mcg', 80),
('Levothyroxine', 'Thyronorm', 'Thyroid', 'tablet', '75mcg', 60),
('Levothyroxine', 'Thyronorm', 'Thyroid', 'tablet', '100mcg', 55),
('Carbimazole', 'Neomercazole', 'Thyroid', 'tablet', '5mg', 40),
('Carbimazole', 'Neomercazole', 'Thyroid', 'tablet', '10mg', 35)

ON CONFLICT DO NOTHING;
